In [1]:
import numpy as np
import pandas as pd
from os import listdir
from os.path import isfile, isdir, join

In [2]:
data_path = '../Data/cleansed_data/'
data = listdir(data_path)
i = 0
for f in data:
    fullpath = join(data_path, f)
    if isfile(fullpath):
        if f.find('csv') != -1:
            df_name = 'df_' + f
            exec("%s = pd.read_csv('%s')" % (df_name[:-4], data_path + f))

In [3]:
#print(df_automobile_sale_01_08,
#      df_automobile_sale_09_19, 
#      df_coal_consump_01_08, 
#      df_coal_consump_09_19, 
#      df_CPI_01_08, 
#      df_CPI_09_19,
#      df_natural_gas_consump_01_08,
#      df_natural_gas_consump_09_19,
#      df_treescover_loss_01_08,
#      df_treescover_loss_09_19,
#      df_US_real_GDP_01_08,
#      df_US_real_GDP_09_19)

           DATE    TOTALSA
0    2001-01-07  17.629145
1    2001-01-14  17.850691
2    2001-01-21  16.499039
3    2001-01-28  14.163210
4    2001-02-04  16.917572
..          ...        ...
412  2008-11-30  10.745410
413  2008-12-07  12.533865
414  2008-12-14  10.298568
415  2008-12-21   9.594489
416  2008-12-28  10.409944

[417 rows x 2 columns]            DATE    TOTALSA
0    2009-01-04  10.535732
1    2009-01-11   8.347124
2    2009-01-18   8.574011
3    2009-01-25   8.961935
4    2009-02-01   9.348876
..          ...        ...
569  2019-12-01  17.941804
570  2019-12-08  14.872529
571  2019-12-15  18.616565
572  2019-12-22  16.962709
573  2019-12-29  17.838750

[574 rows x 2 columns]      Unnamed: 0          Value
0    2001-01-07   96641.568591
1    2001-01-14   89172.960369
2    2001-01-21  100533.687656
3    2001-01-28  101753.621895
4    2001-02-04   61448.503210
..          ...            ...
412  2008-11-30   93144.238565
413  2008-12-07   93097.536737
414  2008-12-14   96031.189959
415  2008-12-21   94626.387757
416  2008-12-28   81948.203787

[417 rows x 2 columns]      Unnamed: 0         Value
0    2009-01-04  80527.669711
1    2009-01-11  81500.879526
2    2009-01-18  97916.981766
3    2009-01-25  84498.026606
4    2009-02-01  89510.777453
..          ...           ...
569  2019-12-01  43325.230944
570  2019-12-08  39751.667961
571  2019-12-15  48847.790991
572  2019-12-22  50008.885420
573  2019-12-29  49428.077912

[574 rows x 2 columns]            DATE  CPALTT01USM661S
0    2001-01-07        78.645985
1    2001-01-14        68.158536
2    2001-01-21        76.149426
3    2001-01-28        76.116224
4    2001-02-04        66.693151
..          ...              ...
412  2008-11-30        99.238162
413  2008-12-07        82.367875
414  2008-12-14        96.265108
415  2008-12-21        92.911057
416  2008-12-28        94.417737

[417 rows x 2 columns]            DATE  CPALTT01USM661S
0    2009-01-04        93.262178
1    2009-01-11        91.817169
2    2009-01-18        91.122475
3    2009-01-25        87.888142
4    2009-02-01        82.715265
..          ...              ...
569  2019-12-01       112.084710
570  2019-12-08       109.471205
571  2019-12-15       108.183411
572  2019-12-22       108.707988
573  2019-12-29       105.725844

[574 rows x 2 columns]            Date  U.S. Natural Gas Residential Consumption (MMcf)
0    2001-01-07                                     9.634759e+05
1    2001-01-14                                     9.010023e+05
2    2001-01-21                                     1.032450e+06
3    2001-01-28                                     8.260147e+05
4    2001-02-04                                     7.766296e+05
..          ...                                              ...
412  2008-11-30                                     4.333457e+05
413  2008-12-07                                     9.989935e+05
414  2008-12-14                                     5.635120e+05
415  2008-12-21                                     7.542331e+05
416  2008-12-28                                     7.034964e+05

[417 rows x 2 columns]            Date  U.S. Natural Gas Residential Consumption (MMcf)
0    2009-01-04                                     1.166511e+06
1    2009-01-11                                     9.357362e+05
2    2009-01-18                                     9.389947e+05
3    2009-01-25                                     9.046054e+05
4    2009-02-01                                     7.992948e+05
..          ...                                              ...
569  2019-12-01                                     6.060118e+05
570  2019-12-08                                     8.286665e+05
571  2019-12-15                                     7.519214e+05
572  2019-12-22                                     5.915937e+05
573  2019-12-29                                     6.146294e+05

[574 rows x 2 columns]      Unnamed: 0  umd_tree_cover_loss__ha
0    2001-01-07             1.932323e+06
1    2001-01-14             2.174659e+06
2    2001-01-21             2.335532e+06
3    2001-01-28             2.065546e+06
4    2001-02-04             1.989476e+06
..          ...                      ...
412  2008-11-30             2.254337e+06
413  2008-12-07             2.031385e+06
414  2008-12-14             2.397440e+06
415  2008-12-21             2.535053e+06
416  2008-12-28             2.044911e+06

[417 rows x 2 columns]      Unnamed: 0  umd_tree_cover_loss__ha
0    2009-01-04             1.406958e+06
1    2009-01-11             1.567991e+06
2    2009-01-18             1.336298e+06
3    2009-01-25             1.652557e+06
4    2009-02-01             1.470782e+06
..          ...                      ...
569  2019-12-01             2.173872e+06
570  2019-12-08             2.458220e+06
571  2019-12-15             1.946026e+06
572  2019-12-22             2.230631e+06
573  2019-12-29             2.124357e+06

[574 rows x 2 columns]            DATE         GDPC1
0    2001-01-07  12999.569899
1    2001-01-14  12293.340526
2    2001-01-21  12708.810379
3    2001-01-28  12287.226546
4    2001-02-04  13353.262835
..          ...           ...
412  2008-11-30  15451.903163
413  2008-12-07  15362.370407
414  2008-12-14  14770.914561
415  2008-12-21  15966.699191
416  2008-12-28  15333.049473

[417 rows x 2 columns]            DATE         GDPC1
0    2009-01-04  14476.249822
1    2009-01-11  16075.155514
2    2009-01-18  15137.191645
3    2009-01-25  15155.344014
4    2009-02-01  15538.171293
..          ...           ...
569  2019-12-01  19477.309102
570  2019-12-08  19750.111124
571  2019-12-15  20106.390381
572  2019-12-22  20396.270073
573  2019-12-29  18812.885384

[574 rows x 2 columns]